apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-ts7b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-ts7b
    app.kubernetes.io/part-of: test-app-oegi
  name: maven-hello-world-ts7b
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-ts7b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-ts7b
    spec:
      containers:
      - image: quay.io/susdas_quay_org/demo/test-app-oegi/maven-hello-world-ts7b@sha256:e85d4719a0e340dbbbf364c810b39bea3334ef773c03d63be649d618f5c245d5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
