apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-gqo5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-gqo5
    app.kubernetes.io/part-of: test-app-oegi
  name: pip-e2e-test-gqo5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-gqo5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-gqo5
    spec:
      containers:
      - image: quay.io/susdas_quay_org/demo/test-app-oegi/pip-e2e-test-gqo5@sha256:2806fef5342eda4cc62673c9a590be8e924ecfaa21b6884fd1083deec119ef2d
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
